stages:
- build
- test

build:
  stage : build
  script: 
    - cd sh-backend
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd sh-backend
    - ./gradlew test
    - ./gradlew.bat --stop