variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
- build
- test
- sonarqube

build:
  stage : build
  script: 
    - cd sh-backend
    - ./gradlew build -x test

test:
  stage: test
  script:
    - cd sh-backend
    - ./gradlew test
    
sonarqube-check:
  stage: sonarqube
  script: 
      - cd sh-backend
      - ./gradlew sonarqube
  allow_failure: true
