variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
- build
- test
- sonarqube
- delivery

build:
  stage : build
  script: 
    - cd sh-backend
    - ./gradlew build -x test

test:
  stage: test
  script:
    - cd sh-backend
    - ./gradlew test
    
sonarqube:
  stage: sonarqube
  script: 
      - cd sh-backend
      - ./gradlew sonarqube
  allow_failure: true
  
delivery:
    stage: delivery
    script:
        - cd sh-backend
        - ./gradlew build -x test
        - cd ..
        - docker-compose build
