stages:
- build
- test
- sonarqube

build:
  stage : build
  script: 
    - cd sh-backend
    - ./gradlew build -x test
    - ./gradlew.bat --stop

test:
  stage: test
  script:
    - cd sh-backend
    - ./gradlew test
    - ./gradlew.bat --stop
    
sonarqube-check:
  stage: sonarqube
  script: 
      - cd sh-backend
      - ./gradlew sonarqube
      - ./gradlew.bat --stop
