services:
  s3-individual:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
        MYSQL_DATABASE: student-housing
        MYSQL_ROOT_PASSWORD: abcde

  roomies-backend:
    build: 
      dockerfile: Dockerfile

    image: roomies/sh-backend
    restart: always
    ports: 
      - 8080:8080
    environment:
      MYSQL_HOST: s3-individual
      MYSQL_USER: root
      MYSQL_PASSWORD: abcde
      MYSQL_PORT: 3306
    depends_on:
      - s3-individual